### ISSUE TITLE
Change libkeyutils-sys to not requite C linking

### ISSUE THREAD

**Issue by josephlr** [mathstuf/rust-keyutils#24]
The current implementation of `libkeyutils-sys` requires linking against the C library `libkeyutils`. However, this seems a bit unnecessary as this library doesn't use any of `libkeyutils` advanced functionality (and it reimplements all the constants), but only needs the wrappers for the three Linux syscalls:
  - [add_key(2)](http://man7.org/linux/man-pages/man2/add_key.2.html)
  - [request_key(2)](http://man7.org/linux/man-pages/man2/request_key.2.html)
  - [keyctl(2)](http://man7.org/linux/man-pages/man2/keyctl.2.html)

I would propose the following design change:
  - Don't use `libkeyutils`
  - Use `libc::syscall` and [std::io::Error::last_os_error](https://doc.rust-lang.org/std/io/struct.Error.html#method.last_os_error) to implement type-safe Rust wrappers around the syscalls.
  - These functions would then be safe, and all `unsafe` code would be limited to the lower-level crate.
  - The `errno` crate could be removed as a dependancy

This changes would probably justify changing the name from `libkeyutils-sys` to `keyutils-raw`.

**Comment by mathstuf** [comment]
I'd be thrilled to do this. However, first I think the test suite should be improved to help ensure that we're not breaking behavior with our implementation. There are some more advanced functionality bits that we're using that are incidental (mainly `EOPNOTSUPP` holes). Most of the extra code we are using seems to be around supporting older kernels without all of the features.
