### ISSUE TITLE
Improve keyutils tests

### ISSUE THREAD

**Issue by josephlr** [mathstuf/rust-keyutils#32]
The [tests from `libkeyutils`](https://git.kernel.org/pub/scm/linux/kernel/git/dhowells/keyutils.git/tree/tests) are quite extensive and would be a good way to check that `keyutils` is properly exposing the kernel keyring API.

We should port these to be Rust integration tests. This will also make future changes like #24 much easier to make with confidence.

**Comment by mathstuf** [comment]
The core tests have been ported since #34. Keytype-specific tests would still be nice to have, but the uplift off of the library shouldn't care about that.
