### ISSUE TITLE
Consider publishing a new release on crates.io

### ISSUE THREAD

**Issue by complexspaces** [mathstuf/rust-keyutils#61]
Hi there,

The [package](https://crates.io/crates/keyutils) for this crate hasn't seen any updates in almost 6 years. However, a large number of improvements have been made since then. This forces potential users to use a Git dependency, and stops use further in the crate ecosystem due to crates.io's publishing restrictions.

I couldn't find any previous issues or PRs about this, so other then time constraints, I'm not certain why its been so long. Assuming you have nothing against it and have the time, would you consider updating the published crate?

**Comment by mathstuf** [comment]
I think another `0.x` release is fine. I never got around to making the keytype impls for what the kernel has today (something I'd like before 1.x). I'll see if I can make some time for it this week.

**Comment by complexspaces** [comment]
Thank you for giving this a look.

**Comment by complexspaces** [comment]
👋 Hey there, this is a friendly ping on this if you have a moment.

**Comment by mathstuf** [comment]
https://crates.io/crates/keyutils/0.4.0

**Comment by complexspaces** [comment]
Thanks a bunch for the release, we appreciate it.

**Comment by mathstuf** [comment]
Indeed :) . Sorry for the delays, just finally getting time to go through and tackle the *long* hobby backlog that's built up since the baby arrived.

**Comment by complexspaces** [comment]
No problem at all, I know exactly where you're coming from with the hobby backlog.
